name = "mcptest-cors-proxy"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
FIREBASE_PROJECT_ID = "mcp-testing"

# Deploy to workers.dev subdomain
# After deployment, the URL will be: https://mcptest-cors-proxy.{your-account}.workers.dev/
# Update VITE_PROXY_URL in your .env file with this URL

# Optional: Configure custom routes if you have a custom domain
# [[routes]]
# pattern = "cors-proxy.mcptest.io/*"
# zone_name = "mcptest.io"