name = "cors-proxy-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
FIREBASE_PROJECT_ID = "mcptest-a530d"

[observability.logs]
enabled = true

# Deploy to workers.dev subdomain
# After deployment, the URL will be: https://cors-proxy-worker.livecart.workers.dev/
# Update VITE_PROXY_URL in your .env file with this URL

# Optional: Configure custom routes if you have a custom domain
# [[routes]]
# pattern = "cors-proxy.mcptest.io/*"
# zone_name = "mcptest.io"