name = "mcptest-io"
main = "src/index.js"
compatibility_date = "2025-07-30"

[vars]
# Replace with your actual Firebase project ID
FIREBASE_PROJECT_ID = "mcptest-a530d"

[durable_objects]
bindings = [
  { name = "USER_STATE", class_name = "UserState" }
]

[[migrations]]
tag = "v1"
new_classes = ["UserState"]