name = "oauth-worker"
main = "src/index.js"
compatibility_date = "2025-08-24"

# KV namespace binding - must be configured in Cloudflare dashboard
# Do NOT add [[kv_namespaces]] here - configure it in Workers & Pages settings
# The binding name MUST be "OAUTH_KV" for the OAuth provider package

# Environment variables (if needed)
[vars]
# Add any environment-specific variables here

# Route configuration (optional - can be configured in Cloudflare dashboard)
# [[routes]]
# pattern = "oauth.yourdomain.com/*"
# zone_name = "yourdomain.com"

[observability.logs]
enabled = true